# Configuración para auto-assign en Pull Requests
# Reemplaza con los usuarios de tu equipo

# Asignar revisores automáticamente
addReviewers: true

# Asignar assignees automáticamente  
addAssignees: false

# Lista de revisores (usuarios de GitHub)
reviewers:
  - tu-usuario
  # - colab1
  # - colab2

# Número de revisores a asignar
numberOfReviewers: 1

# Configuración para assignees (opcional)
# assignees:
#   - tu-usuario

# numberOfAssignees: 1

