# Configuración simplificada de golangci-lint para PayVue

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck      # Verifica errores no manejados
    - gosimple      # Simplificaciones de código
    - govet         # Examina código Go
    - ineffassign   # Asignaciones ineficientes
    - staticcheck   # Análisis estático
    - unused        # Código no usado

linters-settings:
  errcheck:
    check-type-assertions: true
  
  gocyclo:
    min-complexity: 15

issues:
  exclude-rules:
    # Excluir tests
    - path: _test\.go
      linters:
        - errcheck
        - gosec

output:
  format: colored-line-number

