name: 🐛 Bug Report
description: Reportar un error
title: "[Bug]: "
labels: ["bug"]

body:
  - type: textarea
    id: description
    attributes:
      label: Descripción del bug
      placeholder: "Al intentar crear una deuda, la API devuelve error 500"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Pasos para reproducir
      placeholder: |
        1. Ir a '...'
        2. Enviar request a '...'
        3. Ver error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Comportamiento esperado
      placeholder: "La deuda debería crearse exitosamente"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs o mensajes de error
      render: shell

