name: Backport

on:
  pull_request_target:
    types: [closed, labeled]

jobs:
  backport:
    name: Backport PR
    runs-on: ubuntu-latest
    # Solo ejecutar si el PR fue merged (no solo cerrado)
    if: github.event.pull_request.merged == true
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Create backport PR
        uses: korthout/backport-action@v2
        with:
          # Token con permisos para crear PRs
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
          # Crear backport basado en labels
          # Ejemplos de labels:
          # - backport-develop: hace backport a rama develop
          # - backport-v1.x: hace backport a rama release/v1.x
          label_pattern: '^backport-([^ ]+)$'
          
          # Rama objetivo se extrae del label
          # Si el label es "backport-develop", target será "develop"
          target_branches: ${{ github.event.pull_request.labels.*.name }}
          
          # Título del nuevo PR
          pull_title: '[Backport ${target_branch}] ${pull_title}'
          
          # Descripción del nuevo PR
          pull_description: |
            Backport automático de #${pull_number}
            
            ---
            
            ${pull_description}

