name: Docker Build

on:
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        run: docker build -t payvue:latest .

      - name: Test image
        run: |
          docker images payvue:latest
          echo "✅ Imagen Docker creada exitosamente"

