name: PR Checks

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  # Validación de título del PR
  pr-title:
    name: Validar título del PR
    runs-on: ubuntu-latest
    steps:
      - name: Verificar conventional commit
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
          requireScope: false

  # Validación de tamaño del PR
  pr-size:
    name: Verificar tamaño del PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verificar número de archivos cambiados
        run: |
          FILES_CHANGED=$(git diff --name-only origin/${{ github.base_ref }}...HEAD | wc -l)
          echo "Archivos cambiados: $FILES_CHANGED"
          
          if [ $FILES_CHANGED -gt 30 ]; then
            echo "⚠️ El PR tiene más de 30 archivos cambiados ($FILES_CHANGED)"
            echo "Considera dividir este PR en PRs más pequeños"
          fi

      - name: Verificar líneas cambiadas
        run: |
          LINES_CHANGED=$(git diff --shortstat origin/${{ github.base_ref }}...HEAD | grep -oE '[0-9]+ insertions?' | grep -oE '[0-9]+' || echo 0)
          echo "Líneas cambiadas: $LINES_CHANGED"
          
          if [ $LINES_CHANGED -gt 500 ]; then
            echo "⚠️ El PR tiene más de 500 líneas cambiadas ($LINES_CHANGED)"
            echo "Considera dividir este PR en PRs más pequeños"
          fi

  # Verificar que no hay conflictos
  no-conflicts:
    name: Verificar conflictos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verificar conflictos de merge
        run: |
          git fetch origin ${{ github.base_ref }}
          if git merge-tree $(git merge-base HEAD origin/${{ github.base_ref }}) HEAD origin/${{ github.base_ref }} | grep -q '<<<<<<<'; then
            echo "❌ El PR tiene conflictos de merge"
            exit 1
          else
            echo "✅ No hay conflictos de merge"
          fi

  # Verificar que no hay TODOs nuevos
  no-todos:
    name: Verificar TODOs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verificar TODOs nuevos
        run: |
          git fetch origin ${{ github.base_ref }}
          NEW_TODOS=$(git diff origin/${{ github.base_ref }}...HEAD | grep -i "^+.*TODO" | wc -l)
          
          if [ $NEW_TODOS -gt 0 ]; then
            echo "⚠️ Se encontraron $NEW_TODOS TODOs nuevos:"
            git diff origin/${{ github.base_ref }}...HEAD | grep -i "^+.*TODO"
            echo ""
            echo "Considera resolver estos TODOs antes de hacer merge"
          else
            echo "✅ No se encontraron TODOs nuevos"
          fi

  # Verificar dependencias
  dependencies:
    name: Verificar dependencias
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Verificar go.mod y go.sum
        run: |
          go mod tidy
          if [ -n "$(git status --porcelain go.mod go.sum)" ]; then
            echo "❌ go.mod o go.sum no están sincronizados"
            echo "Ejecuta 'go mod tidy' y haz commit de los cambios"
            git diff go.mod go.sum
            exit 1
          else
            echo "✅ go.mod y go.sum están sincronizados"
          fi

      - name: Verificar vulnerabilidades
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck ./...

  # Comentar en el PR con el resumen
  comment:
    name: Comentar resumen
    runs-on: ubuntu-latest
    needs: [pr-title, pr-size, no-conflicts, no-todos, dependencies]
    if: always()
    steps:
      - name: Crear comentario de resumen
        uses: actions/github-script@v7
        with:
          script: |
            const results = {
              'Título del PR': '${{ needs.pr-title.result }}',
              'Tamaño del PR': '${{ needs.pr-size.result }}',
              'Conflictos': '${{ needs.no-conflicts.result }}',
              'TODOs': '${{ needs.no-todos.result }}',
              'Dependencias': '${{ needs.dependencies.result }}'
            };
            
            let comment = '## 🔍 Resumen de validaciones del PR\n\n';
            
            for (const [check, result] of Object.entries(results)) {
              const emoji = result === 'success' ? '✅' : result === 'failure' ? '❌' : '⚠️';
              comment += `${emoji} **${check}**: ${result}\n`;
            }
            
            comment += '\n---\n';
            comment += '*Este comentario fue generado automáticamente por CI*';
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });

